### ISSUE TITLE
Bug in no script code

### ISSUE THREAD

**Issue by bdillahu** [MichelePalmieri/grav-piwik-plugin#1]
The piwik.php file, line 44, has the siteID hardcoded...

I believe the line should be:

<noscript><p><img src=\"{$sitePiWikURL}/piwik.php?idsite={$siteId}\" style=\"border:0;\" alt=\"\" /></p></noscript>

**Comment by MichelePalmieri** [comment]
fixed bug

**Comment by bdillahu** [comment]
Just wanted to mention that for whatever reason, the "bin/gpm update" or "bin/gpm install piwik" isn't getting the new version.

**Comment by MichelePalmieri** [comment]
ok
