### ISSUE TITLE
set up

### ISSUE THREAD

**Issue by tidiview** [MichelePalmieri/grav-piwik-plugin#2]
Thank you for this plugin.

I would like to use it but I don't understand set up.

Could precise what is the **Piwik ID url**?

Do you have to download Piwik from Piwik web site, then run it to get the **Piwik ID url** then insert it into the plugin?

Is that it?

Thanks in advance for your help

**Comment by MichelePalmieri** [comment]
1) Install piwik -> http://piwik.org/docs/installation/
2) Set up Your Website -> https://piwik.org/docs/installation/#set-up-your-first-website
3) Admin menu
3A) Manage Websites
 ![cattura](https://cloud.githubusercontent.com/assets/9617683/11431517/fa7b02f4-9499-11e5-862c-7afcbc647aa0.PNG)
3B) "ID" of your site
![cattura2](https://cloud.githubusercontent.com/assets/9617683/11431518/0760dce6-949a-11e5-9756-7840984be5f1.PNG)
