### ISSUE TITLE
seems to miss a part in your piwik.php

### ISSUE THREAD

**Issue by JOduMonT** [MichelePalmieri/grav-piwik-plugin#4]
1' When I use your plugin, my website ask me to authentificate myself on my piwik

2' it seems to miss a part in your piwik.php

Just after 
do you miss this line ? 
`<script type="text/javascript">
`

**Comment by geschke** [comment]
I think this is not valid anymore. The JavaScript part starts with "<script>" in the same way as in some Grav plugins. 
Thanks for your request!
