### ISSUE TITLE
Image Tracking Link is missing http:

### ISSUE THREAD

**Issue by Johanhen** [MichelePalmieri/grav-piwik-plugin#7]
The included code is missing http:
it looks like this 

  <img src="//piwik.mydomain.nl/piwik.php?idsite=1&rec=1" style="border:0" alt="" />
It should look like this
 <img src="**http:**//piwik.mydomain.nl/piwik.php?idsite=1&rec=1" style="border:0" alt="" />
regards
Johan Hendriks

**Comment by Johanhen** [comment]
Nice it removed some code!!
img src="//piwik.mydomain.com/piwik.php?idsite=1&rec=1" style="border:0" alt=""
it should be 
img src="http://piwik.mydomain.com/piwik.php?idsite=1&rec=1" style="border:0" alt=""

**Comment by geschke** [comment]
Please have a look at a previous pull request. There protocol isn't missing. The reason is:

> Please have a look at a current version of Piwik. I'm running self-hosted Piwik 3.0.1 and have taken the embed code from this version. See the line below:
> 
> var u="//analytics.mushaake.org/";
> The advantage of this method is, that it is working with both protocols http and https without predefining the used protocol. Piwik is available with http and https, so it runs in every case. The browser uses the protocol which is used on the main site.
> 
See https://github.com/MichelePalmieri/grav-piwik-plugin/pull/5

Kind regards,
   Ralf

**Comment by Johanhen** [comment]
If I go to the tracking code page for my site the var u="// is like you mentioned.
If i scrool down the page it shows me the following
Image Tracking

When a visitor has disabled JavaScript, or when JavaScript cannot be used, you can use an image tracking link to track visitors. Generate the link below and copy-paste the generated HTML in the page. If you're using this as a fallback for JavaScript tracking, you can surround it in <noscript></noscript> tags.
For the whole list of options you can use with an image tracking link, see the Tracking API Documentation.

Then further down it shows me the code and there it has set http://
Image Tracking Link

 Piwik Image Tracker
img src="http://piwik.mydomain.com/piwik.php?idsite=1&rec=1" style="border:0" alt="" />
End Piwik

**Comment by geschke** [comment]
Yes, but what happens if the protocol is removed? Does it work or not? I guess it's ok, although Piwik includes it in the example code. 

See here https://stackoverflow.com/questions/4978235/absolute-urls-omitting-the-protocol-scheme-in-order-to-preserve-the-one-of-the and here https://stackoverflow.com/questions/550038/is-it-valid-to-replace-http-with-in-a-script-src-http (there is a reference to RFC 2396), or here https://stackoverflow.com/questions/954327/hidden-features-of-html/960111#960111 .

**Comment by Johanhen** [comment]
Sorry for the late reply.
For me it is working if i have disabled java. So java code is not executed and the img src=http:// method gives me data.
As there is no java it can not fill in the http or https itself.

regards
Johan

**Comment by geschke** [comment]
Sorry, but did you read the submitted texts? It is no difference between JavaScript is disabled or not, the urls are valid!

Kind regards,
   Ralf

**Comment by MichelePalmieri** [comment]
I started renaming 
https://github.com/MichelePalmieri/grav-matomo-plugin
We'll see
